server:
  port: 8002
spring:
  application:
    name: customer-movie-feign-with-hystrix-factory

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #自定义注册实例的格式
    # leaseRenewalIntervalInSeconds: 10 # change the time register service time 修改服务注册时间慢的问题
# 解决feign第一次请求失败，hystrix默认配置为1为超时，超过1s，进入fallback
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

logging.level.org.ywb.study.feignclient.UserFeignClient: DEBUG