server:
  port: 8761
eureka:
  client:
    register-with-eureka: false   #单机模式下，不需要被自己注册，eureka本身是server，也是client
    fetch-registry: false
    service-url:
      defauleZone: http://user:password@localhost:8761/eureka #http://localhost:8761/eureka，在服务注册是机器上访问也需要使用curl格式的权限认证

# 添加对eureka的认证，需要引入 spring-boot-start-security 的依赖
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
