server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: provider-user
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.description.sql.BasicBinder: trace
    org.hibernate.type.description.sql.BaseExtractor: trace
    org.ywb: debug
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka # http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 将服务的地址映射为ip
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #自定义注册实例的格式
    # leaseRenewalIntervalInSeconds: 10 # change the time register service time 修改服务注册时间慢的问题
